#!/usr/bin/env python3
"""Generate the Unicode properties required for XML normalization checks."""

from __future__ import annotations

import argparse
import unicodedata
from pathlib import Path

UNICODE_VERSION = "15.1.0"
MAX_CODEPOINT = 0x10FFFF


def ranges(values: list[tuple[int, int]]) -> list[tuple[int, int, int]]:
    result: list[tuple[int, int, int]] = []
    for codepoint, value in values:
        if result and result[-1][1] + 1 == codepoint and result[-1][2] == value:
            first, _, previous = result[-1]
            result[-1] = first, codepoint, previous
        else:
            result.append((codepoint, codepoint, value))
    return result


def set_ranges(values: list[int]) -> list[tuple[int, int]]:
    result: list[tuple[int, int]] = []
    for codepoint in values:
        if result and result[-1][1] + 1 == codepoint:
            result[-1] = result[-1][0], codepoint
        else:
            result.append((codepoint, codepoint))
    return result


def scalar(codepoint: int) -> bool:
    return codepoint < 0xD800 or 0xDFFF < codepoint <= MAX_CODEPOINT


def known(codepoint: int) -> bool:
    return (
        unicodedata.category(chr(codepoint)) != "Cn"
        or 0xFDD0 <= codepoint <= 0xFDEF
        or codepoint & 0xFFFF in (0xFFFE, 0xFFFF)
    )


def algorithmic_hangul_pair(first: int, second: int) -> bool:
    return (0x1100 <= first <= 0x1112 and 0x1161 <= second <= 0x1175) or (
        0xAC00 <= first <= 0xD7A3
        and (first - 0xAC00) % 28 == 0
        and 0x11A8 <= second <= 0x11C2
    )


def generated_data() -> tuple[
    list[tuple[int, int]],
    list[tuple[int, int, int]],
    list[tuple[int, int]],
    list[tuple[int, int]],
    list[tuple[int, int, int]],
]:
    known_codepoints: list[int] = []
    combining: list[tuple[int, int]] = []
    nfc_no: list[int] = []
    composing: set[int] = set()
    compositions: list[tuple[int, int, int]] = []

    for codepoint in range(MAX_CODEPOINT + 1):
        if not scalar(codepoint):
            continue
        character = chr(codepoint)
        if known(codepoint):
            known_codepoints.append(codepoint)
        combining_class = unicodedata.combining(character)
        if combining_class:
            combining.append((codepoint, combining_class))
            composing.add(codepoint)
        if unicodedata.normalize("NFC", character) != character:
            nfc_no.append(codepoint)

        decomposition = unicodedata.decomposition(character)
        if not decomposition or decomposition.startswith("<"):
            continue
        parts = tuple(int(value, 16) for value in decomposition.split())
        if len(parts) != 2:
            continue
        # Hangul composition is implemented algorithmically in canCompose.
        if algorithmic_hangul_pair(*parts):
            continue
        pair = "".join(chr(value) for value in parts)
        if unicodedata.normalize("NFC", pair) != character:
            continue
        compositions.append((parts[0], parts[1], codepoint))
        composing.add(parts[1])

    composing.update(range(0x1161, 0x1176))
    composing.update(range(0x11A8, 0x11C3))
    compositions.sort()
    return (
        set_ranges(known_codepoints),
        ranges(combining),
        set_ranges(nfc_no),
        set_ranges(sorted(composing)),
        compositions,
    )


def hex_value(value: int) -> str:
    return f"0x{value:x}"


def render() -> str:
    if unicodedata.unidata_version != UNICODE_VERSION:
        raise SystemExit(
            f"requires Unicode {UNICODE_VERSION}, found {unicodedata.unidata_version}"
        )
    known_codepoints, combining, nfc_no, composing, compositions = generated_data()
    lines = [
        "//! Unicode normalization properties used by the XML 1.1 reader.",
        "//!",
        f"//! Generated by `tools/python/generate-unicode-normalization.py` from Unicode {UNICODE_VERSION}.",
        "",
        "const Range = struct { first: u21, last: u21 };",
        "const ClassRange = struct { first: u21, last: u21, value: u8 };",
        "const Composition = struct { first: u21, second: u21 };",
        "",
        "pub const Issue = enum { not_nfc, unknown_character };",
        "",
        "pub const Checker = struct {",
        "    starter: ?u21 = null,",
        "    previous_class: u8 = 0,",
        "",
        "    pub fn reset(self: *Checker) void {",
        "        self.* = .{};",
        "    }",
        "",
        "    pub fn add(self: *Checker, codepoint: u21) ?Issue {",
        "        if (codepoint < 0x80) {",
        "            self.starter = codepoint;",
        "            self.previous_class = 0;",
        "            return null;",
        "        }",
        "        if (!inRanges(&KNOWN_CODEPOINTS, codepoint)) return .unknown_character;",
        "        if (inRanges(&NFC_NO, codepoint)) return .not_nfc;",
        "        const class = combiningClass(codepoint);",
        "        if (class != 0 and self.previous_class > class) return .not_nfc;",
        "        if (self.starter) |starter| {",
        "            if ((self.previous_class == 0 or self.previous_class < class) and",
        "                canCompose(starter, codepoint)) return .not_nfc;",
        "        }",
        "        if (class == 0) self.starter = codepoint;",
        "        self.previous_class = class;",
        "        return null;",
        "    }",
        "};",
        "",
        "pub fn isComposing(codepoint: u21) ?bool {",
        "    if (!inRanges(&KNOWN_CODEPOINTS, codepoint)) return null;",
        "    return inRanges(&COMPOSING, codepoint);",
        "}",
        "",
        "fn combiningClass(codepoint: u21) u8 {",
        "    var low: usize = 0;",
        "    var high: usize = COMBINING_CLASSES.len;",
        "    while (low < high) {",
        "        const middle = low + (high - low) / 2;",
        "        const entry = COMBINING_CLASSES[middle];",
        "        if (codepoint < entry.first) high = middle else if (codepoint > entry.last) low = middle + 1 else return entry.value;",
        "    }",
        "    return 0;",
        "}",
        "",
        "fn canCompose(first: u21, second: u21) bool {",
        "    if (first >= 0x1100 and first <= 0x1112 and second >= 0x1161 and second <= 0x1175) return true;",
        "    if (first >= 0xac00 and first <= 0xd7a3 and (first - 0xac00) % 28 == 0 and second >= 0x11a8 and second <= 0x11c2) return true;",
        "    var low: usize = 0;",
        "    var high: usize = COMPOSITIONS.len;",
        "    while (low < high) {",
        "        const middle = low + (high - low) / 2;",
        "        const entry = COMPOSITIONS[middle];",
        "        if (first < entry.first or (first == entry.first and second < entry.second)) {",
        "            high = middle;",
        "        } else if (first > entry.first or (first == entry.first and second > entry.second)) {",
        "            low = middle + 1;",
        "        } else return true;",
        "    }",
        "    return false;",
        "}",
        "",
        "fn inRanges(entries: []const Range, codepoint: u21) bool {",
        "    var low: usize = 0;",
        "    var high: usize = entries.len;",
        "    while (low < high) {",
        "        const middle = low + (high - low) / 2;",
        "        const entry = entries[middle];",
        "        if (codepoint < entry.first) high = middle else if (codepoint > entry.last) low = middle + 1 else return true;",
        "    }",
        "    return false;",
        "}",
        "",
    ]

    def append_ranges(name: str, entries: list[tuple[int, int]]) -> None:
        lines.append(f"const {name} = [_]Range{{")
        for first, last in entries:
            lines.append(
                f"    .{{ .first = {hex_value(first)}, .last = {hex_value(last)} }},"
            )
        lines.extend(("};", ""))

    append_ranges("KNOWN_CODEPOINTS", known_codepoints)
    append_ranges("NFC_NO", nfc_no)
    append_ranges("COMPOSING", composing)

    lines.append("const COMBINING_CLASSES = [_]ClassRange{")
    for first, last, value in combining:
        lines.append(
            f"    .{{ .first = {hex_value(first)}, .last = {hex_value(last)}, .value = {value} }},"
        )
    lines.extend(("};", ""))

    lines.append("const COMPOSITIONS = [_]Composition{")
    for first, second, _ in compositions:
        lines.append(
            f"    .{{ .first = {hex_value(first)}, .second = {hex_value(second)} }},"
        )
    lines.extend(("};", ""))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the output instead of rewriting it",
    )
    args = parser.parse_args()
    generated = render()
    if args.check:
        try:
            observed = args.output.read_text(encoding="utf-8")
        except OSError as error:
            print(f"unable to read {args.output}: {error}")
            return 1
        if observed != generated:
            print(f"generated Unicode table differs from {args.output}")
            return 1
        print(f"generated Unicode table matches {args.output}")
        return 0
    args.output.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
