//! Streaming XML Writer state, ownership, limits, and errors.

const std = @import("std");

const reader = @import("reader.zig");

/// Limits for Writer-owned active state and retained allocation capacity.
pub const WriterLimits = struct {
    /// Finite default limits for the Writer.
    pub const general: WriterLimits = .{};

    /// Maximum simultaneously open element count.
    max_depth: usize = 256,
    /// Maximum cumulative UTF-8 bytes retained for open element names.
    max_open_name_bytes: usize = 1024 * 1024,
    /// Maximum UTF-8 bytes accepted in one qualified name.
    max_qname_bytes: usize = 64 * 1024,
    /// Maximum attributes accepted on one element.
    max_attributes_per_element: usize = 256,
    /// Maximum namespace declarations accepted on one element.
    max_namespace_declarations_per_element: usize = 64,
    /// Maximum active namespace bindings, including shadowed bindings.
    max_active_namespace_bindings: usize = 1024,
    /// Maximum prefix and URI bytes retained by active namespace bindings.
    max_namespace_binding_bytes: usize = 1024 * 1024,
    /// Maximum generated bytes retained for one pending start tag.
    max_pending_start_tag_bytes: usize = 1024 * 1024,
    /// Maximum Writer-owned allocation capacity retained at one time.
    max_retained_bytes: usize = 2 * 1024 * 1024,

    fn valid(self: WriterLimits) bool {
        return self.max_depth > 0 and
            self.max_open_name_bytes > 0 and
            self.max_qname_bytes > 0 and
            self.max_attributes_per_element > 0 and
            self.max_namespace_declarations_per_element > 0 and
            self.max_active_namespace_bindings > 0 and
            self.max_namespace_binding_bytes > 0 and
            self.max_pending_start_tag_bytes > 0 and
            self.max_retained_bytes > 0;
    }
};

/// Runtime XML output choices.
pub const WriterOptions = struct {
    /// Resource limits applied independently of sink capacity.
    limits: WriterLimits = WriterLimits.general,
    /// Selects namespace-aware or raw-name writing.
    namespaces: reader.NormalNamespacePolicy = .process,
    /// Selects XML 1.0 or XML 1.1 output rules.
    version: reader.XmlVersion = .xml10,
    /// Writes the XML declaration when true.
    emit_declaration: bool = true,
    /// Writes the declaration's standalone value when non-null.
    standalone: ?bool = null,

    fn valid(self: WriterOptions) bool {
        return self.limits.valid() and (self.emit_declaration or self.standalone == null);
    }
};

/// Errors reported while constructing a Writer.
pub const WriterInitError = error{InvalidOptions};

/// Errors reported by mutating Writer calls.
pub const WriterError = error{
    InvalidState,
    InvalidName,
    InvalidCharacter,
    InvalidNamespace,
    DuplicateAttribute,
    WriterLimit,
    WriteFailed,
    OutOfMemory,
};

/// Active logical counts and retained allocation capacity owned by a Writer.
pub const WriterMemoryUsage = struct {
    /// Number of currently open elements.
    open_element_count: usize,
    /// UTF-8 bytes retained for open element names.
    open_name_bytes: usize,
    /// Active namespace bindings, including shadowed bindings.
    namespace_binding_count: usize,
    /// Prefix and URI bytes retained by active namespace bindings.
    namespace_bytes: usize,
    /// Attributes retained for the current pending start tag.
    pending_attribute_count: usize,
    /// Generated bytes retained for the current pending start tag.
    pending_start_tag_bytes: usize,
    /// Total Writer-owned allocation capacity measured in bytes.
    retained_capacity_bytes: usize,
};

const Lifecycle = enum {
    ready,
    prolog,
    start_tag,
    content,
    epilog,
    done,
    failed,
};

/// Stateful UTF-8 XML writer over a caller-owned sink.
///
/// The allocator and sink remain borrowed until `deinit`. The Writer never
/// flushes or deinitializes the sink. Copying an initialized Writer is not supported.
/// Calls are not thread-safe or reentrant.
pub const Writer = struct {
    allocator: std.mem.Allocator,
    sink: *std.Io.Writer,
    options: WriterOptions,
    lifecycle: Lifecycle = .ready,
    open_element_count: usize = 0,
    first_failure: ?WriterError = null,
    logical_byte_offset: u64 = 0,
    offset_valid: bool = true,

    /// Returns a ready Writer without allocating or writing to `sink`.
    pub fn init(
        allocator: std.mem.Allocator,
        sink: *std.Io.Writer,
        options: WriterOptions,
    ) WriterInitError!Writer {
        if (!options.valid()) return error.InvalidOptions;

        return .{
            .allocator = allocator,
            .sink = sink,
            .options = options,
        };
    }

    /// Releases Writer-owned storage without flushing or deinitializing the sink.
    pub fn deinit(self: *Writer) void {
        self.* = undefined;
    }

    /// Starts one XML document.
    pub fn startDocument(self: *Writer) WriterError!void {
        try self.checkFailure();
        if (self.lifecycle != .ready) return self.fail(error.InvalidState);
        self.lifecycle = .prolog;
    }

    /// Starts one root or child element and leaves its start tag pending.
    pub fn startElement(self: *Writer, name: []const u8) WriterError!void {
        try self.checkFailure();
        _ = name;

        switch (self.lifecycle) {
            .prolog, .start_tag, .content => {},
            else => return self.fail(error.InvalidState),
        }
        if (self.open_element_count == self.options.limits.max_depth) {
            return self.fail(error.WriterLimit);
        }

        self.open_element_count += 1;
        self.lifecycle = .start_tag;
    }

    /// Adds one namespace declaration to the pending start tag.
    pub fn namespace(
        self: *Writer,
        prefix: ?[]const u8,
        namespace_uri: []const u8,
    ) WriterError!void {
        try self.checkFailure();
        _ = prefix;
        _ = namespace_uri;
        if (self.lifecycle != .start_tag) return self.fail(error.InvalidState);
    }

    /// Adds one attribute to the pending start tag.
    pub fn attribute(self: *Writer, name: []const u8, value: []const u8) WriterError!void {
        try self.checkFailure();
        _ = name;
        _ = value;
        if (self.lifecycle != .start_tag) return self.fail(error.InvalidState);
    }

    /// Writes one character-data fragment inside the current element.
    pub fn text(self: *Writer, bytes: []const u8) WriterError!void {
        try self.enterContent();
        _ = bytes;
    }

    /// Writes one CDATA fragment inside the current element.
    pub fn cdata(self: *Writer, bytes: []const u8) WriterError!void {
        try self.enterContent();
        _ = bytes;
    }

    /// Writes one comment in the prolog, current element, or epilog.
    pub fn comment(self: *Writer, bytes: []const u8) WriterError!void {
        try self.checkFailure();
        _ = bytes;

        switch (self.lifecycle) {
            .prolog, .content, .epilog => {},
            .start_tag => self.lifecycle = .content,
            else => return self.fail(error.InvalidState),
        }
    }

    /// Writes one processing instruction in the prolog, current element, or epilog.
    pub fn processingInstruction(
        self: *Writer,
        target: []const u8,
        data: []const u8,
    ) WriterError!void {
        try self.checkFailure();
        _ = target;
        _ = data;

        switch (self.lifecycle) {
            .prolog, .content, .epilog => {},
            .start_tag => self.lifecycle = .content,
            else => return self.fail(error.InvalidState),
        }
    }

    /// Ends the current element without requiring the caller to repeat its name.
    pub fn endElement(self: *Writer) WriterError!void {
        try self.checkFailure();
        switch (self.lifecycle) {
            .start_tag, .content => {},
            else => return self.fail(error.InvalidState),
        }
        std.debug.assert(self.open_element_count > 0);

        self.open_element_count -= 1;
        self.lifecycle = if (self.open_element_count == 0) .epilog else .content;
    }

    /// Completes one document without flushing the caller-owned sink.
    pub fn endDocument(self: *Writer) WriterError!void {
        try self.checkFailure();
        if (self.lifecycle != .epilog) return self.fail(error.InvalidState);
        self.lifecycle = .done;
    }

    /// Returns the complete logical UTF-8 byte count, or null after a write failure.
    pub fn byteOffset(self: *const Writer) ?u64 {
        return if (self.offset_valid) self.logical_byte_offset else null;
    }

    /// Reports Writer-owned active state and retained allocation capacity.
    pub fn memoryUsage(self: *const Writer) WriterMemoryUsage {
        return .{
            .open_element_count = self.open_element_count,
            .open_name_bytes = 0,
            .namespace_binding_count = 0,
            .namespace_bytes = 0,
            .pending_attribute_count = 0,
            .pending_start_tag_bytes = 0,
            .retained_capacity_bytes = 0,
        };
    }

    fn enterContent(self: *Writer) WriterError!void {
        try self.checkFailure();
        switch (self.lifecycle) {
            .start_tag, .content => self.lifecycle = .content,
            else => return self.fail(error.InvalidState),
        }
    }

    fn checkFailure(self: *Writer) WriterError!void {
        if (self.first_failure) |failure| return failure;
    }

    fn fail(self: *Writer, failure: WriterError) WriterError {
        std.debug.assert(self.first_failure == null);
        self.first_failure = failure;
        self.lifecycle = .failed;
        if (failure == error.WriteFailed) self.offset_valid = false;
        return failure;
    }
};
